### ISSUE TITLE
Hardcoded subdivision

### ISSUE THREAD

**Issue by sarantos92** [Vatsim-Scandinavia/discord-bot#33]
https://github.com/Vatsim-Scandinavia/discord-bot/blob/12a2765c476fff08c7e222fb845391aaaa3816dd/cogs/tasks.py#L67
https://github.com/Vatsim-Scandinavia/discord-bot/blob/12a2765c476fff08c7e222fb845391aaaa3816dd/cogs/tasks.py#L69

**Comment by sarantos92** [comment]
https://github.com/Vatsim-Scandinavia/discord-bot/blob/12a2765c476fff08c7e222fb845391aaaa3816dd/bot.py#L67

https://github.com/Vatsim-Scandinavia/discord-bot/blob/12a2765c476fff08c7e222fb845391aaaa3816dd/bot.py#L69

**Comment by Marko259** [comment]
Closed in 327a84fd162513e2cfc814870c8f41d923ffc723
