### ISSUE TITLE
possible bug on subdivision change?

### ISSUE THREAD

**Issue by sarantos92** [Vatsim-Scandinavia/discord-bot#41]
if one member leave/change the subdivision, it doesnt remove the role from discord

**Comment by blt950** [comment]
I'll let @Marko259 look into this.

@sarantos92 can you elaborate the issue? Which role? Mentor role? vACC role?

**Comment by sarantos92** [comment]
For example if a member leave the subdivision and run /checkusers or on
automatic run it doesn’t remove the role of vatsca

Στις Δευ, 17 Ιαν 2022 στις 00:05 ο χρήστης Daniel ***@***.***>
έγραψε:
