### ISSUE TITLE
Creating new event seems to have old desc in memory?

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/discord-bot#46]
When I re-created an old event, after editing the old. It seems perhaps old event description was in memory when I wrote the new event and the new event text.

Creating for some reason had the old description in memory perhaps? See screenshot, what I wrote vs. what I got. What I got was the old description from the previous event. Looks like perhaps some variable not reseting
![2022-03-27 09_30_34-web-bot - Discord](https://user-images.githubusercontent.com/2505044/160272608-ae1f1935-8147-4483-878c-867ac997f08b.png)
![2022-03-27 09_30_47-staffing-bgo-tuesday - Discord](https://user-images.githubusercontent.com/2505044/160272610-5248f3dd-7fbd-4a71-9499-e65b53ddf1a2.png)
?

**Comment by Marko259** [comment]
@blt950 This is not a bug, the bot is doing as it is supposed to since we some time ago added these phrases to the end of each description `To book a position, write /book, press TAB and then write the callsign` and `To unbook a position, use /unbook`.

**Comment by blt950** [comment]
I'm a retard 😂
