### ISSUE TITLE
Tweak suggestions

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/discord-bot#47]
When recreating events recently I came to think of a few tweak suggestions.

- [x] When running /updatestaffing make the menu selection like in unix. Type number to select, rather than typing the whole words
- [x] When asking for staffing name, add a note that it needs to be identical to the event itself. Otherwise the time won't sync properly.Perhaps deny events that don't match event name to avoid sql problems further down the line
- [x] Add Zulu time duration for events upon creating it. Right now it only adds it to the description when updating instead.
- [x] Add command to refresh event details (time etc) as today the only way is to update staffing msg

**Comment by Marko259** [comment]
Fixed in 233c2c8
