### ISSUE TITLE
Pre/post bookings event functionality

### ISSUE THREAD

**Issue by blt950** [Vatsim-Scandinavia/discord-bot#66]
Requested functionality where Discord staffing list will reflect bookings from CC prior and after event. E.g. pulling the bookings each X minutes.

**Comment by Marko259** [comment]
Example of this could look like this

![image](https://user-images.githubusercontent.com/26257478/215889326-8b930021-bf85-4015-a573-36a40f1b54ee.png)

**Comment by Marko259** [comment]
Added in #74
